name: Build on Ubuntu

on: [push, pull_request]

jobs:
  build_qt:
    name: With QT GUI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: install packages
      run: |
        sudo add-apt-repository ppa:mhier/libboost-latest
        sudo apt-get update
        sudo apt-get install build-essential qt5-default libqt5gui5 libboost1.74-dev libminiupnpc-dev libssl-dev zlib1g-dev
    - name: build application
      run: |
        qmake
        make -j$(nproc)
